#
# Copyright 2016 LINE Corporation
#
# LINE Corporation licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

#This is a template for the configuration file.
#Make a copy called `application.yml` and change the values below.

line.bot:
  channel-token: 'tk1m5ddFWRR2vLNd9aqx/b6KDzxjv0RV0e6aU617QwObtZDXSv0vy8ZL7kNNmSDOTDAZosdqMoD2uWlOSg7wWfhzifk7+lyxMzLGpZm+rmBe+WLgul5Ly8EAzuoZlzVEQRBYkIKxFTFUxklI242KBQdB04t89/1O/w1cDnyilFU='
  channel-secret: '14b9cd9e6a56344c49fba7dac5ec689f'
  handler.path: /callback


# To remove Client wire logs. Please comment out following lines.
# See: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html
#
#logging.level:
#   com.linecorp.bot.client.wire: INFO
